blueprint:
  name: IKEA Styrbar (Z2M)
  description: Define actions for press and hold on all four buttons of the E2001_E2002 switch.
  domain: automation
  author: Nico Thomaier
  input:
    controller_device:
      name: (Zigbee2MQTT) Controller Device
      description: The action device of the controller to use for the automation.
      default: ""
      selector:
        device:
          multiple: false
    on:
      name: On Pressed
      default: []
      selector:
        action: {}
    off:
      name: Off Pressed
      default: []
      selector:
        action: {}
    brightness_move_up:
      name: Brightness Move Up
      default: []
      selector:
        action: {}
    brightness_move_down:
      name: Brightness Move Down
      default: []
      selector:
        action: {}
    brightness_stop:
      name: Brightness Stop
      default: []
      selector:
        action: {}
    arrow_left_click:
      name: Arrow Left Clicked
      default: []
      selector:
        action: {}
    arrow_right_click:
      name: Arrow Right Clicked
      default: []
      selector:
        action: {}

  source_url: https://community.home-assistant.io/t/ikea-styrbar-e2001-2002-ultimate-zigbee2mqtt-z2m/625090
mode: single
max_exceeded: silent


trigger:
  - platform: state
    device_id: !input controller_device
    attribute: action
    # Prefent double automation triggers in restart mode
    not_to: ""

# triggers:
#   - trigger: device
#     domain: mqtt
#     device_id: !input controller_device
#     type: action
#     id: "on"
#     subtype: "on"
#   - trigger: device
#     domain: mqtt
#     device_id: !input controller_device
#     type: action
#     id: "brightness_move_up"
#     subtype: "brightness_move_up"
#   - trigger: device
#     domain: mqtt
#     device_id: !input controller_device
#     type: action
#     id: "off"
#     subtype: "off"
#   - trigger: device
#     domain: mqtt
#     device_id: !input controller_device
#     type: action
#     id: "brightness_move_down"
#     subtype: "brightness_move_down"
#   - trigger: device
#     domain: mqtt
#     device_id: !input controller_device
#     type: action
#     id: "arrow_left_click"
#     subtype: "arrow_left_click"
#   - trigger: device
#     domain: mqtt
#     device_id: !input controller_device
#     type: action
#     id: "arrow_right_click"
#     subtype: "arrow_right_click"
#   - trigger: device
#     domain: mqtt
#     device_id: !input controller_device
#     type: action
#     id: "arrow_left_hold"
#     subtype: "arrow_left_hold"
#   - trigger: device
#     domain: mqtt
#     device_id: !input controller_device
#     type: action
#     id: "arrow_right_hold"
#     subtype: "arrow_right_hold"

action:
  - variables:
      trigger_action: "{{ trigger.id }}"
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "on" }}'
        sequence: !input light_large_push
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "brightness_move_up" }}'
        sequence: !input light_large_hold
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "off" }}'
        sequence: !input light_small_push
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "brightness_move_down" }}'
        sequence: !input light_small_hold
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_left_click" }}'
        sequence: !input arrow_left_push
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_left_hold" }}'
        sequence: !input arrow_left_hold
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_right_click" }}'
        sequence: !input arrow_right_push
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_right_hold" }}'
        sequence: !input arrow_right_hold