blueprint:
  name: IKEA Styrbar (Z2M) - Auto Light Control with CT + Continuous Dimming (device-only)
  description: >
    On/off, brightness up/down with continuous dimming, and color temperature left/right.
    Arrow left/right do nothing if the light is off.
  domain: automation
  author: Modified from Nico Thomaier

  input:
    controller_device:
      name: (Zigbee2MQTT) Controller Device
      description: The action device of the controller to use for the automation.
      default: ""
      selector:
        device:
          multiple: false

    target_light:
      name: Target Light or Light Group
      selector:
        entity:
          domain: light

    brightness_step_pct:
      name: Brightness step per tick (%)
      default: 2
      selector:
        number:
          min: 1
          max: 20
          step: 1
          mode: slider
          unit_of_measurement: "%"

    ct_step:
      name: Color temperature step (mireds)
      default: 25
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider

    "on":
      name: On Pressed (extra actions after turning on)
      default: []
      selector:
        action: {}
    "off":
      name: Off Pressed (extra actions after turning off)
      default: []
      selector:
        action: {}
    brightness_move_up:
      name: Brightness Move Up (extra actions after raising brightness / hold)
      default: []
      selector:
        action: {}
    brightness_move_down:
      name: Brightness Move Down (extra actions after lowering brightness / hold)
      default: []
      selector:
        action: {}
    brightness_stop:
      name: Brightness Stop (extra actions after releasing hold)
      default: []
      selector:
        action: {}
    arrow_left_click:
      name: Arrow Left Clicked (extra actions after CT change)
      default: []
      selector:
        action: {}
    arrow_right_click:
      name: Arrow Right Clicked (extra actions after CT change)
      default: []
      selector:
        action: {}

mode: single
max_exceeded: silent

trigger:
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "on"
    subtype: "on"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "off"
    subtype: "off"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "brightness_move_up"
    subtype: "brightness_move_up"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "brightness_move_down"
    subtype: "brightness_move_down"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "arrow_left_click"
    subtype: "arrow_left_click"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "arrow_right_click"
    subtype: "arrow_right_click"

action:
  - variables:
      trigger_action: "{{ trigger.id }}"
      target: !input target_light

  - choose:
      # ---------------------------- TURN ON OR OFF ---------------------------- #
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "on" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input on

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "off" }}'
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input off

      # ------------------- CONTINUOUS DIMMING (HOLD) -------------------- #
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "brightness_move_up" }}'
        sequence:
          - variables:
              pct: !input brightness_step_pct
          - repeat:
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input target_light
                  data:
                    brightness_step_pct: "{{ pct }}"
                    transition: 0.1
                - wait_for_trigger:
                    - platform: device
                      domain: mqtt
                      device_id: !input controller_device
                      type: action
                      subtype: brightness_stop
                  timeout: 0.1
                  continue_on_timeout: true
              until:
                - condition: template
                  value_template: "{{ wait.trigger is not none }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input brightness_move_up
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input brightness_stop

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "brightness_move_down" }}'
        sequence:
          - variables:
              pct: !input brightness_step_pct
          - repeat:
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input target_light
                  data:
                    brightness_step_pct: "{{ -pct }}"
                    transition: 0.1
                - wait_for_trigger:
                    - platform: device
                      domain: mqtt
                      device_id: !input controller_device
                      type: action
                      subtype: brightness_stop
                  timeout: 0.1
                  continue_on_timeout: true
              until:
                - condition: template
                  value_template: "{{ wait.trigger is not none }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input brightness_move_down
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input brightness_stop

      # ------------------------ COLOR TEMPERATURE ------------------------ #
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_left_click" }}'
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input target_light
                    state: "on"
                sequence:
                  - variables:
                      min_ct: "{{ state_attr(target, 'min_mireds') | default(153) }}"
                      max_ct: "{{ state_attr(target, 'max_mireds') | default(500) }}"
                      step_ct: !input ct_step
                      cur_ct: "{{ state_attr(target, 'color_temp') | default(((min_ct + max_ct) // 2), true) }}"
                      new_ct: "{{ [cur_ct - step_ct, min_ct] | max }}"
                  - service: light.turn_on
                    target:
                      entity_id: !input target_light
                    data:
                      color_temp: "{{ new_ct }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "true"
                        sequence: !input arrow_left_click
            default: []
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_right_click" }}'
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input target_light
                    state: "on"
                sequence:
                  - variables:
                      min_ct: "{{ state_attr(target, 'min_mireds') | default(153) }}"
                      max_ct: "{{ state_attr(target, 'max_mireds') | default(500) }}"
                      step_ct: !input ct_step
                      cur_ct: "{{ state_attr(target, 'color_temp') | default(((min_ct + max_ct) // 2), true) }}"
                      new_ct: "{{ [cur_ct + step_ct, max_ct] | min }}"
                  - service: light.turn_on
                    target:
                      entity_id: !input target_light
                    data:
                      color_temp: "{{ new_ct }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "true"
                        sequence: !input arrow_right_click
            default: []