blueprint:
  name: IKEA Styrbar Colortemp & Dimmer (Z2M, move-friendly)
  description: >
    Styrbar control optimized for IKEA LED2107C4: uses Zigbee2MQTT move/stop for continuous dimming to prevent flooding.
    - On sets brightness.
    - Off toggles or turns on at a set level.
    - Hold brightness up/down starts a single move command; release sends stop.
    - Left/right adjust color temperature (only when ON).
    - If z2m_topic is empty, falls back to step dimming at a slower rate without transition.
  domain: automation
  author: Nico Thomaier (modified)

  input:
    controller_device:
      name: (Zigbee2MQTT) Controller Device
      description: The action device of the controller to use for the automation.
      default: ""
      selector:
        device:
          multiple: false

    target_light:
      name: Target Light or Light Group
      description: Select the light entity (single light or light group) to control.
      selector:
        entity:
          domain: light

    # On/Off behavior
    on_brightness_pct:
      name: Brightness when pressing On (%)
      default: 50
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"

    off_turn_on_brightness_pct:
      name: Brightness when pressing Off while lights are OFF (%)
      default: 25
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"

    # Dimming config
    use_move:
      name: Use Zigbee2MQTT move/stop for continuous dimming
      description: Recommended for IKEA bulbs to prevent flooding.
      default: true
      selector:
        boolean: {}

    move_rate:
      name: Move rate (units per second)
      description: Positive moves up, negative moves down. Typical = 40.
      default: 40
      selector:
        number:
          min: 10
          max: 100
          step: 5
          mode: slider

    z2m_topic:
      name: Zigbee2MQTT topic (friendly name or Zigbee2MQTT group name)
      description: Example: LivingRoomLamp or BedroomGroup. Leave empty to use step fallback.
      default: ""
      selector:
        text: {}

    # Fallback step config
    brightness_step_pct:
      name: Brightness step per tick (%) [fallback only]
      default: 10
      selector:
        number:
          min: 1
          max: 20
          step: 1
          mode: slider
          unit_of_measurement: "%"

    step_interval:
      name: Fallback step interval (seconds)
      default: 0.3
      selector:
        number:
          min: 0.2
          max: 1.0
          step: 0.1
          mode: slider

    # Color temp
    ct_step:
      name: Color temperature step (mireds)
      default: 25
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider

    # Extra actions
    "on":
      name: On Pressed (extra actions after turning on)
      default: []
      selector:
        action: {}
    "off":
      name: Off Pressed (extra actions after turning off / Off-to-On)
      default: []
      selector:
        action: {}
    brightness_move_up:
      name: Brightness Move Up (extra actions after raising brightness / hold)
      default: []
      selector:
        action: {}
    brightness_move_down:
      name: Brightness Move Down (extra actions after lowering brightness / hold)
      default: []
      selector:
        action: {}
    brightness_stop:
      name: Brightness Stop (extra actions after releasing hold)
      default: []
      selector:
        action: {}
    arrow_left_click:
      name: Arrow Left Clicked (extra actions after CT change)
      default: []
      selector:
        action: {}
    arrow_right_click:
      name: Arrow Right Clicked (extra actions after CT change)
      default: []
      selector:
        action: {}

  source_url: https://community.home-assistant.io/t/ikea-styrbar-e2001-2002-ultimate-zigbee2mqtt-z2m/625090

mode: single
max_exceeded: silent

trigger:
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "on"
    subtype: "on"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "off"
    subtype: "off"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "brightness_move_up"
    subtype: "brightness_move_up"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "brightness_move_down"
    subtype: "brightness_move_down"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "arrow_left_click"
    subtype: "arrow_left_click"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "arrow_right_click"
    subtype: "arrow_right_click"

action:
  - variables:
      trigger_action: "{{ trigger.id }}"
      target: !input target_light
      use_move: !input use_move
      move_rate: !input move_rate
      z2m_topic: !input z2m_topic
      step_pct: !input brightness_step_pct
      step_interval: !input step_interval

  - choose:
      # ---------------------------- TURN ON ---------------------------- #
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "on" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_pct: !input on_brightness_pct
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input on

      # -------- OFF: TURN OFF OR TURN ON AT SET BRIGHTNESS WHEN CURRENTLY OFF -------- #
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "off" }}'
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input target_light
                    state: "off"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input target_light
                    data:
                      brightness_pct: !input off_turn_on_brightness_pct
            default:
              - service: light.turn_off
                target:
                  entity_id: !input target_light
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input off

      # ------------------- CONTINUOUS DIMMING (HOLD) -------------------- #
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "brightness_move_up" }}'
        sequence:
          - choose:
              # Preferred: Zigbee2MQTT move/stop
              - conditions:
                  - condition: template
                    value_template: '{{ use_move and (z2m_topic | length) > 0 }}'
                sequence:
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: !input target_light
                            state: "off"
                        sequence:
                          # Use ..._onoff so the bulb turns on while starting the move
                          - service: mqtt.publish
                            data:
                              topic: "zigbee2mqtt/{{ z2m_topic }}/set"
                              payload: '{{ {"brightness_move_onoff": move_rate} | tojson }}'
                    default:
                      - service: mqtt.publish
                        data:
                          topic: "zigbee2mqtt/{{ z2m_topic }}/set"
                          payload: '{{ {"brightness_move": move_rate} | tojson }}'
                  - wait_for_trigger:
                      - platform: device
                        domain: mqtt
                        device_id: !input controller_device
                        type: action
                        subtype: brightness_stop
                    timeout: "00:05:00"
                    continue_on_timeout: true
                  - service: mqtt.publish
                    data:
                      topic: "zigbee2mqtt/{{ z2m_topic }}/set"
                      payload: '{{ {"brightness_move": 0} | tojson }}'
              # Fallback: slower step without transition
              - conditions:
                  - condition: template
                    value_template: "{{ not use_move or (z2m_topic | length) == 0 }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: !input target_light
                            state: "off"
                        sequence:
                          - service: light.turn_on
                            target:
                              entity_id: !input target_light
                  - repeat:
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: !input target_light
                          data:
                            brightness_step_pct: "{{ step_pct }}"
                        - wait_for_trigger:
                            - platform: device
                              domain: mqtt
                              device_id: !input controller_device
                              type: action
                              subtype: brightness_stop
                          timeout: "{{ step_interval }}"
                          continue_on_timeout: true
                      until:
                        - condition: template
                          value_template: "{{ wait.trigger is not none }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input brightness_move_up
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input brightness_stop

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "brightness_move_down" }}'
        sequence:
          - choose:
              # Preferred: Zigbee2MQTT move/stop
              - conditions:
                  - condition: template
                    value_template: '{{ use_move and (z2m_topic | length) > 0 }}'
                sequence:
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: !input target_light
                            state: "off"
                        sequence:
                          - service: mqtt.publish
                            data:
                              topic: "zigbee2mqtt/{{ z2m_topic }}/set"
                              payload: '{{ {"brightness_move_onoff": (0 - move_rate)} | tojson }}'
                    default:
                      - service: mqtt.publish
                        data:
                          topic: "zigbee2mqtt/{{ z2m_topic }}/set"
                          payload: '{{ {"brightness_move": (0 - move_rate)} | tojson }}'
                  - wait_for_trigger:
                      - platform: device
                        domain: mqtt
                        device_id: !input controller_device
                        type: action
                        subtype: brightness_stop
                    timeout: "00:05:00"
                    continue_on_timeout: true
                  - service: mqtt.publish
                    data:
                      topic: "zigbee2mqtt/{{ z2m_topic }}/set"
                      payload: '{{ {"brightness_move": 0} | tojson }}'
              # Fallback: slower step without transition
              - conditions:
                  - condition: template
                    value_template: "{{ not use_move or (z2m_topic | length) == 0 }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: !input target_light
                            state: "off"
                        sequence:
                          - service: light.turn_on
                            target:
                              entity_id: !input target_light
                  - repeat:
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: !input target_light
                          data:
                            brightness_step_pct: "{{ (0 - step_pct) }}"
                        - wait_for_trigger:
                            - platform: device
                              domain: mqtt
                              device_id: !input controller_device
                              type: action
                              subtype: brightness_stop
                          timeout: "{{ step_interval }}"
                          continue_on_timeout: true
                      until:
                        - condition: template
                          value_template: "{{ wait.trigger is not none }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input brightness_move_down
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input brightness_stop

      # ------------------------ COLOR TEMPERATURE (only if light is ON) ------------------------ #
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_left_click" }}'
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input target_light
                    state: "on"
                sequence:
                  - variables:
                      min_ct: "{{ state_attr(target, 'min_mireds') | default(153) }}"
                      max_ct: "{{ state_attr(target, 'max_mireds') | default(500) }}"
                      step_ct: !input ct_step
                      cur_ct: "{{ state_attr(target, 'color_temp') | default(((min_ct + max_ct) // 2), true) }}"
                      new_ct: "{{ [cur_ct - step_ct, min_ct] | max }}"
                  - service: light.turn_on
                    target:
                      entity_id: !input target_light
                    data:
                      color_temp: "{{ new_ct }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "true"
                        sequence: !input arrow_left_click
            default: []

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_right_click" }}'
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input target_light
                    state: "on"
                sequence:
                  - variables:
                      min_ct: "{{ state_attr(target, 'min_mireds') | default(153) }}"
                      max_ct: "{{ state_attr(target, 'max_mireds') | default(500) }}"
                      step_ct: !input ct_step
                      cur_ct: "{{ state_attr(target, 'color_temp') | default(((min_ct + max_ct) // 2), true) }}"
                      new_ct: "{{ [cur_ct + step_ct, max_ct] | min }}"
                  - service: light.turn_on
                    target:
                      entity_id: !input target_light
                    data:
                      color_temp: "{{ new_ct }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "true"
                        sequence: !input arrow_right_click
            default: []