blueprint:
  name: IKEA Styrbar (Z2M) - Color Temp Control
  description: >
    Define actions for press and hold on all four buttons of the E2001_E2002 switch.
    Adds built-in color temperature control on left/right arrow clicks for the selected light.
  domain: automation
  author: Nico Thomaier (modified)
  input:
    controller_device:
      name: (Zigbee2MQTT) Controller Device
      description: The action device of the controller to use for the automation.
      default: ""
      selector:
        device:
          multiple: false

    target_light:
      name: Target Light (color temperature capable)
      description: Select the light entity to control color temperature on arrow left/right clicks.
      selector:
        entity:
          domain: light

    ct_step:
      name: Color temperature step (mireds)
      description: How much to change per arrow click (lower mireds = cooler, higher = warmer).
      default: 25
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider

    "on":
      name: On Pressed
      default: []
      selector:
        action: {}
    "off":
      name: Off Pressed
      default: []
      selector:
        action: {}
    brightness_move_up:
      name: Brightness Move Up
      default: []
      selector:
        action: {}
    brightness_move_down:
      name: Brightness Move Down
      default: []
      selector:
        action: {}
    brightness_stop:
      name: Brightness Stop
      default: []
      selector:
        action: {}
    arrow_left_click:
      name: Arrow Left Clicked (extra actions after CT change)
      default: []
      selector:
        action: {}
    arrow_right_click:
      name: Arrow Right Clicked (extra actions after CT change)
      default: []
      selector:
        action: {}

  source_url: https://community.home-assistant.io/t/ikea-styrbar-e2001-2002-ultimate-zigbee2mqtt-z2m/625090

mode: single
max_exceeded: silent

trigger:
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "on"
    subtype: "on"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "off"
    subtype: "off"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "brightness_move_up"
    subtype: "brightness_move_up"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "brightness_move_down"
    subtype: "brightness_move_down"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "arrow_left_click"
    subtype: "arrow_left_click"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "arrow_right_click"
    subtype: "arrow_right_click"

action:
  - variables:
      trigger_action: "{{ trigger.id }}"

  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "on" }}'
        sequence: !input on

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "brightness_move_up" }}'
        sequence: !input brightness_move_up

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "off" }}'
        sequence: !input off

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "brightness_move_down" }}'
        sequence: !input brightness_move_down

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_left_click" }}'
        sequence:
          - variables:
              target: !input target_light
              min_ct: "{{ state_attr(target, 'min_mireds') | default(153) }}"
              max_ct: "{{ state_attr(target, 'max_mireds') | default(500) }}"
              step: !input ct_step
              cur_ct: "{{ state_attr(target, 'color_temp') | default(((min_ct + max_ct) // 2), true) }}"
              new_ct: "{{ [cur_ct - step, min_ct] | max }}"
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              color_temp: "{{ new_ct }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input arrow_left_click

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_right_click" }}'
        sequence:
          - variables:
              target: !input target_light
              min_ct: "{{ state_attr(target, 'min_mireds') | default(153) }}"
              max_ct: "{{ state_attr(target, 'max_mireds') | default(500) }}"
              step: !input ct_step
              cur_ct: "{{ state_attr(target, 'color_temp') | default(((min_ct + max_ct) // 2), true) }}"
              new_ct: "{{ [cur_ct + step, max_ct] | min }}"
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              color_temp: "{{ new_ct }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input arrow_right_click