blueprint:
  name: IKEA Styrbar (Z2M) - Auto Light Control with CT
  description: >
    Based on the original Styrbar (Z2M) blueprint, this version automatically controls
    the configured target light or light group:
    - "on"/"off" turn lights on/off
    - "brightness_move_up"/"brightness_move_down" increase/decrease brightness by a step
    - "arrow_left_click"/"arrow_right_click" change color temperature by a step
    Optional extra actions can be added for each event and run after the default behavior.
  domain: automation
  author: Modified from Nico Thomaier
  input:
    controller_device:
      name: (Zigbee2MQTT) Controller Device
      description: The action device of the controller to use for the automation.
      default: ""
      selector:
        device:
          multiple: false

    target_light:
      name: Target Light or Light Group
      description: Select the light entity (single light or light group) to control.
      selector:
        entity:
          domain: light

    brightness_step:
      name: Brightness step (1-255)
      description: Amount to change brightness per click.
      default: 25
      selector:
        number:
          min: 1
          max: 255
          step: 1
          mode: slider

    ct_step:
      name: Color temperature step (mireds)
      description: Amount to change color temperature per left/right arrow click.
      default: 25
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider

    "on":
      name: On Pressed (extra actions after turning on)
      default: []
      selector:
        action: {}
    "off":
      name: Off Pressed (extra actions after turning off)
      default: []
      selector:
        action: {}
    brightness_move_up:
      name: Brightness Move Up (extra actions after raising brightness)
      default: []
      selector:
        action: {}
    brightness_move_down:
      name: Brightness Move Down (extra actions after lowering brightness)
      default: []
      selector:
        action: {}
    brightness_stop:
      name: Brightness Stop (reserved for future continuous dimming)
      default: []
      selector:
        action: {}
    arrow_left_click:
      name: Arrow Left Clicked (extra actions after CT change)
      default: []
      selector:
        action: {}
    arrow_right_click:
      name: Arrow Right Clicked (extra actions after CT change)
      default: []
      selector:
        action: {}

  source_url: https://community.home-assistant.io/t/ikea-styrbar-e2001-2002-ultimate-zigbee2mqtt-z2m/625090

mode: single
max_exceeded: silent

trigger:
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "on"
    subtype: "on"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "off"
    subtype: "off"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "brightness_move_up"
    subtype: "brightness_move_up"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "brightness_move_down"
    subtype: "brightness_move_down"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "arrow_left_click"
    subtype: "arrow_left_click"
  - platform: device
    domain: mqtt
    device_id: !input controller_device
    type: action
    id: "arrow_right_click"
    subtype: "arrow_right_click"

action:
  - variables:
      trigger_action: "{{ trigger.id }}"
      target: !input target_light

  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "on" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input on

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "off" }}'
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input off

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "brightness_move_up" }}'
        sequence:
          - variables:
              step: !input brightness_step
              cur_bri: "{{ state_attr(target, 'brightness') | default(0) }}"
              new_bri: "{{ [cur_bri + step, 255] | min }}"
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness: "{{ new_bri }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input brightness_move_up

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "brightness_move_down" }}'
        sequence:
          - variables:
              step: !input brightness_step
              cur_bri: "{{ state_attr(target, 'brightness') | default(0) }}"
              new_bri: "{{ [cur_bri - step, 1] | max }}"
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness: "{{ new_bri }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input brightness_move_down

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_left_click" }}'
        sequence:
          - variables:
              min_ct: "{{ state_attr(target, 'min_mireds') | default(153) }}"
              max_ct: "{{ state_attr(target, 'max_mireds') | default(500) }}"
              step_ct: !input ct_step
              cur_ct: "{{ state_attr(target, 'color_temp') | default(((min_ct + max_ct) // 2), true) }}"
              new_ct: "{{ [cur_ct - step_ct, min_ct] | max }}"
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              color_temp: "{{ new_ct }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input arrow_left_click

      - conditions:
          - condition: template
            value_template: '{{ trigger_action == "arrow_right_click" }}'
        sequence:
          - variables:
              min_ct: "{{ state_attr(target, 'min_mireds') | default(153) }}"
              max_ct: "{{ state_attr(target, 'max_mireds') | default(500) }}"
              step_ct: !input ct_step
              cur_ct: "{{ state_attr(target, 'color_temp') | default(((min_ct + max_ct) // 2), true) }}"
              new_ct: "{{ [cur_ct + step_ct, max_ct] | min }}"
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              color_temp: "{{ new_ct }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "true"
                sequence: !input arrow_right_click